// <auto-generated />
using ElectronicCommerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectronicCommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ElectronicCommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "很好",
                            ImageUrl = "https://img14.360buyimg.com/n1/s546x546_jfs/t1/26576/18/18347/282563/62c55483Ed138ae22/b74923e09acaa7e9.jpg",
                            Price = 3099m,
                            Title = "美的(Midea)606升变频一级能效对开双门家用冰箱京东小家智能家电风冷无霜BCD-606WKPZM(E)大容量精细分储"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            ImageUrl = "",
                            Price = 9.99m,
                            Title = ""
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            ImageUrl = "",
                            Price = 9.99m,
                            Title = ""
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            ImageUrl = "",
                            Price = 9.99m,
                            Title = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
